import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
WALLET_DIR = os.path.join(PROJECT_ROOT, "core", "wallet")

conn = oracledb.connect(
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    dsn=os.getenv("DB_DSN"),
    config_dir=WALLET_DIR,
    wallet_location=WALLET_DIR,
    wallet_password=os.getenv("DB_PASSWORD")
)

cursor = conn.cursor()

# Find all identity columns
cursor.execute("""
    SELECT table_name, column_name, generation_type 
    FROM user_tab_identity_cols
    ORDER BY table_name
""")
id_cols = cursor.fetchall()

print(f"Found {len(id_cols)} identity columns in Oracle DB:")
for row in id_cols:
    tbl, col, gen_type = row
    
    try:
        # Get max value from table safely
        cursor.execute(f'SELECT NVL(MAX("{col}"), 0) FROM "{tbl}"')
        max_val = cursor.fetchone()[0]
    except Exception as e_max:
        print(f"Error querying MAX for \"{tbl}\".\"{col}\": {e_max}")
        continue
        
    print(f"Aligning \"{tbl}\".\"{col}\" (Current MAX = {max_val})")
    
    success = False
    for sql in [
        f'ALTER TABLE "{tbl}" MODIFY ("{col}" GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE))',
        f'ALTER TABLE "{tbl}" MODIFY ("{col}" GENERATED BY DEFAULT AS IDENTITY (START WITH LIMIT VALUE))',
        f'ALTER TABLE "{tbl}" MODIFY ("{col}" GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE))',
        f'ALTER TABLE "{tbl}" MODIFY ("{col}" GENERATED BY DEFAULT ON NULL AS IDENTITY (RESTART START WITH {max_val + 10}))',
        f'ALTER TABLE "{tbl}" MODIFY ("{col}" GENERATED BY DEFAULT AS IDENTITY (RESTART START WITH {max_val + 10}))'
    ]:
        try:
            cursor.execute(sql)
            print(f"  SUCCESS: {sql}")
            success = True
            break
        except Exception as e:
            pass
            
    if not success:
        print(f"  WARNING: Could not align \"{tbl}\".\"{col}\"")

conn.commit()
conn.close()
print("Done aligning sequences.")
