import sqlite3
import oracledb
import os

# Oracle Credentials
DB_USER = "admin"
DB_PASSWORD = "$@P%5WCUgMnb"
DB_DSN = "kumihodb_high"
WALLET_DIR = os.path.join(os.path.dirname(__file__), "core", "wallet")

def map_sqlite_type_to_oracle(sqlite_type: str) -> str:
    sqlite_type = sqlite_type.upper()
    if "INT" in sqlite_type:
        return "NUMBER"
    elif "CHAR" in sqlite_type or "TEXT" in sqlite_type or "CLOB" in sqlite_type:
        return "CLOB" if "CLOB" in sqlite_type else "VARCHAR2(4000)"
    elif "REAL" in sqlite_type or "FLOA" in sqlite_type or "DOUB" in sqlite_type:
        return "NUMBER"
    elif "DATE" in sqlite_type or "TIME" in sqlite_type:
        return "TIMESTAMP"
    elif "BLOB" in sqlite_type:
        return "BLOB"
    else:
        return "VARCHAR2(4000)" # Default to text

def create_table_in_oracle(ora_cursor, table_name, columns_info):
    """
    Creates a table in Oracle based on SQLite PRAGMA table_info.
    columns_info: list of tuples (cid, name, type, notnull, dflt_value, pk)
    """
    cols = []
    pk_cols = []
    
    for col in columns_info:
        col_name = col[1].upper()
        col_type = map_sqlite_type_to_oracle(col[2])
        is_not_null = "NOT NULL" if col[3] else ""
        
        # SQLite's AUTOINCREMENT
        # We can simulate AUTOINCREMENT with GENERATED ALWAYS AS IDENTITY in Oracle
        # But for migration, we need to insert explicit IDs, so we use GENERATED BY DEFAULT AS IDENTITY
        # if the column is a primary key and is an integer.
        extra = ""
        if col[5] > 0: # It's a primary key
            pk_cols.append(col_name)
            if "NUMBER" in col_type and len([c for c in columns_info if c[5] > 0]) == 1:
                # If single-column integer PK, it might be autoincrement
                # We add generated by default so we can still insert the old IDs
                extra = "GENERATED BY DEFAULT AS IDENTITY"
        
        # Handle DEFAULT CURRENT_TIMESTAMP
        if col[4] is not None:
            default_val = col[4]
            if "CURRENT_TIMESTAMP" in default_val.upper():
                default_val = "SYSTIMESTAMP"
            elif default_val.upper() in ["NULL", "''"]:
                pass # let it be
            else:
                extra += f" DEFAULT {default_val}"
                
        if col_name == "LEVEL":
            col_name = '"LEVEL"'
            
        cols.append(f"{col_name} {col_type} {extra} {is_not_null}".strip())
    
    pk_constraint = ""
    if pk_cols:
        quoted_pks = [f'"{c}"' if c == "LEVEL" else c for c in pk_cols]
        pk_constraint = f", PRIMARY KEY ({', '.join(quoted_pks)})"
        
    query = f"CREATE TABLE {table_name.upper()} ({', '.join(cols)}{pk_constraint})"
    
    try:
        ora_cursor.execute(f"DROP TABLE {table_name.upper()}")
    except oracledb.DatabaseError:
        pass # Ignore if doesn't exist
        
    print(f"Creating table {table_name}...")
    ora_cursor.execute(query)

def migrate_table(sqlite_conn, ora_cursor, table_name):
    # Get columns
    sqlite_cursor = sqlite_conn.cursor()
    sqlite_cursor.execute(f"PRAGMA table_info({table_name})")
    columns_info = sqlite_cursor.fetchall()
    
    create_table_in_oracle(ora_cursor, table_name, columns_info)
    
    # Fetch all data
    sqlite_cursor.execute(f"SELECT * FROM {table_name}")
    rows = sqlite_cursor.fetchall()
    
    if not rows:
        print(f"  - No data to migrate for {table_name}.")
        return

    # Prepare INSERT query
    col_names = [f'"{col[1].upper()}"' if col[1].upper() == "LEVEL" else col[1].upper() for col in columns_info]
    binds = [f":{i+1}" for i in range(len(col_names))]
    insert_query = f"INSERT INTO {table_name.upper()} ({', '.join(col_names)}) VALUES ({', '.join(binds)})"
    
    print(f"  - Migrating {len(rows)} rows into {table_name}...")
    
    # Oracle executemany needs rows to be tuples or lists. SQLite fetchall returns tuples.
    # Convert empty strings to None (Oracle treats '' as NULL for VARCHAR2, which can cause issues if not mapped, but usually it's fine).
    ora_cursor.executemany(insert_query, rows)

def main():
    print("Connecting to Oracle Database (mTLS in Thin mode)...")
    
    try:
        ora_conn = oracledb.connect(
            user=DB_USER,
            password=DB_PASSWORD,
            dsn=DB_DSN,
            config_dir=WALLET_DIR,
            wallet_location=WALLET_DIR,
            wallet_password=DB_PASSWORD
        )
        ora_conn.autocommit = True
        ora_cursor = ora_conn.cursor()
        
        # ORA-01843 için NLS tarih/saat formatlarını ayarla (SQLite formatı YYYY-MM-DD HH24:MI:SS)
        ora_cursor.execute("ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'")
        ora_cursor.execute("ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS'")
        
        print("Connected to Oracle Database successfully!")
        
        print("Connecting to local SQLite database...")
        sqlite_conn = sqlite3.connect("rescued_kumiho.db")
        sqlite_cursor = sqlite_conn.cursor()
        
        # Get all tables
        sqlite_cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
        tables = [row[0] for row in sqlite_cursor.fetchall()]
        
        for table in tables:
            try:
                migrate_table(sqlite_conn, ora_cursor, table)
            except Exception as e:
                print(f"ERROR migrating table {table}: {e}")
                
        print("Migration completed!")
        
    except Exception as e:
        print(f"Connection/Migration failed: {e}")

if __name__ == "__main__":
    main()
