import json
import os

translations = {
    # Moderasyon
    "automod": "Sunucudaki otomatik moderasyon sistemini yönetir (küfür, link, spam koruması).",
    "automod antizalgo": "Kullanıcı isimlerinde ve mesajlarda Zalgo (bozuk/taşan metin) kullanımını engeller.",
    "automod antilink": "Sunucuda link (bağlantı) paylaşımını otomatik olarak siler ve uyarır.",
    "automod antiprofanity": "Sunucuda küfür ve kötü söz kullanımını otomatik olarak engeller.",
    "automod whitelist": "Otomatik moderasyonun göz ardı edeceği beyaz liste (whitelist) ayarlarını gösterir.",
    "automod whitelist add": "Otomatik moderasyondan etkilenmeyecek yeni bir kanal, rol veya kelime ekler.",
    "automod whitelist remove": "Beyaz listedeki bir kanalı, rolü veya kelimeyi siler.",
    "automod antispam": "Kullanıcıların art arda mesaj atarak spam yapmasını engeller.",
    "kick": "Belirtilen kullanıcıyı sunucudan atar.",
    "ban": "Belirtilen kullanıcıyı sunucudan kalıcı olarak yasaklar.",
    "unban": "Yasaklanmış bir kullanıcının banını kaldırır.",
    "timeout": "Kullanıcıya belirli bir süreliğine mesaj yazma/sesli sohbet yasağı verir (Mute).",
    "untimeout": "Kullanıcının zaman aşımı (Timeout) cezasını kaldırır.",
    "purge": "Belirtilen sayıdaki mesajı toplu olarak siler.",
    "warn": "Kullanıcıya moderasyon sistemi üzerinden uyarı verir.",
    "warns": "Bir kullanıcının aldığı tüm uyarıları listeler.",
    "clearwarn": "Bir kullanıcının uyarı geçmişini temizler.",
    "vmute": "Kullanıcıyı sesli kanalda susturur.",
    "vunmute": "Kullanıcının sesli kanaldaki susturmasını kaldırır.",
    "vdeafen": "Kullanıcının sesli kanalda diğerlerini duymasını (sağırlaşmasını) sağlar.",
    "vundeafen": "Kullanıcının sağırlaştırma cezasını kaldırır.",
    "vdisconnect": "Kullanıcıyı bulunduğu sesli kanaldan zorla çıkarır.",
    "vmove": "Kullanıcıyı bulunduğu sesli kanaldan başka bir sesli kanala taşır.",
    "create_channel": "Sunucuda yeni bir metin veya ses kanalı oluşturur.",
    "delete_channel": "Belirtilen kanalı sunucudan siler.",
    "nuke": "Bulunulan kanalı siler ve aynı izinlerle kopyasını oluşturur (Kanalı sıfırlar).",
    "modlogs": "Moderasyon işlemlerinin loglandığı kanalı ayarlar veya gösterir.",
    
    # Gelişim ve Ekonomi
    "perk": "Ekonomi sistemi üzerinden satın alınabilen avantajları gösterir.",
    "perk color": "Kullanıcının isminin veya profilinin rengini değiştirmesini sağlar.",
    "perk title": "Kullanıcının özel profil başlığını ayarlar.",
    "balance": "Kullanıcının cüzdanındaki ve bankasındaki mevcut bakiyesini gösterir.",
    "deposit": "Cüzdandaki parayı güvende tutmak için bankaya yatırır.",
    "withdraw": "Bankadaki parayı harcamak için cüzdana çeker.",
    "daily": "Kullanıcıya 24 saatte bir verilen günlük ödülü tahsil eder.",
    "work": "Çalışarak para kazanmanızı sağlar.",
    "beg": "Başkalarından veya sistemden dilenerek para kazanma şansı sunar.",
    "fish": "Balık tutarak rastgele eşya veya para kazanmanızı sağlar.",
    "hunt": "Avlanarak değerli eşyalar ve para kazanmanızı sağlar.",
    "mine": "Maden kazarak değerli taşlar ve para kazanmanızı sağlar.",
    "shop": "Paranızla eşyalar satın alabileceğiniz marketi gösterir.",
    "buy": "Marketten belirtilen eşyayı satın alır.",
    "sell": "Envanterinizdeki bir eşyayı satarak paraya çevirir.",
    "inventory": "Sahip olduğunuz tüm eşyaları listeler.",
    "use": "Envanterinizdeki kullanılabilir bir eşyayı kullanır.",
    "slots": "Slot makinesi oynayarak paranızı katlama şansı sunar (Kumar).",
    "gamble": "Mevcut paranızla kumar oynayarak risk almanızı sağlar.",
    "roulette": "Rulet masasında şansınızı denemenizi sağlar.",
    "blackjack": "Krupiyeye karşı Blackjack (21) oynayarak paranızı katlar.",
    "highlow": "Bir sonraki sayının yüksek mi düşük mü olacağını tahmin ettiğiniz oyundur.",
    "crime": "Suç işleyerek büyük para kazanma şansı sunar (Yakalanırsanız para kaybedersiniz).",
    "scratch": "Kazı kazan kartı alarak şansınızı denemenizi sağlar.",
    "rob": "Başka bir kullanıcının cüzdanındaki parayı çalmayı dener.",
    "pay": "Başka bir kullanıcıya kendi cüzdanınızdan para transfer eder.",
    "marry": "Sunucudaki başka bir kullanıcıyla evlenmenizi sağlar.",
    "divorce": "Evli olduğunuz kullanıcıdan boşanmanızı sağlar.",
    "profile": "Kullanıcının seviye, ekonomi ve evlilik durumunu içeren detaylı profilini gösterir.",
    "leaderboard": "Sunucudaki en zengin kullanıcıların sıralamasını gösterir.",
    "cooldowns": "Komutları tekrar kullanabilmek için beklemeniz gereken süreleri gösterir.",
    "farm": "Kendi sanal tarlanızı yönetmenizi sağlar.",
    "farm harvest": "Tarlanızdaki olgunlaşmış ekinleri hasat eder.",
    "farm plant": "Tarlanıza yeni tohumlar eker.",
    "farm status": "Tarlanızın genel durumunu ve ekinlerin büyüme aşamalarını gösterir.",
    "farm water": "Ekinlerin büyümesini hızlandırmak için tarlanızı sular.",
    "rank": "Kullanıcının mevcut seviyesini ve XP durumunu gösterir.",
    "level": "Sunucunun seviye sistemini yapılandırmanızı sağlar.",
    "level reward_remove": "Belirli bir seviyeye ulaşıldığında verilen rol ödülünü siler.",
    "level ignore_add": "Belirtilen kanal veya rolün seviye (XP) kazanmasını engeller.",
    "level reward_add": "Kullanıcılar belirli bir seviyeye ulaştığında otomatik verilecek rolü ayarlar.",
    "level channel": "Seviye atlama mesajlarının gönderileceği kanalı yönetir.",
    "level channel remove": "Seviye atlama mesajı gönderilen kanalı sistemden siler.",
    "level channel set": "Seviye atlama mesajlarının gönderileceği kanalı belirler.",
    "level reward_list": "Sunucudaki tüm seviye ödüllerini listeler.",
    "level xp_rate": "Sunucudaki XP kazanma hızını (çarpanını) yönetir.",
    "level xp_rate set": "Mesaj başına kazanılacak XP çarpanını belirler (Örn: 2x XP).",
    "level ignore_remove": "XP kazanımı engellenmiş kanal veya rolün engelini kaldırır.",
    "leaderboard_xp": "Sunucudaki en yüksek seviyeye sahip kullanıcıların sıralamasını gösterir.",
    
    # Topluluk ve Etkileşim
    "giveaway": "Çekiliş sistemini yönetir.",
    "giveaway start": "Belirtilen süre ve ödül ile yeni bir çekiliş başlatır.",
    "giveaway list": "Sunucudaki aktif çekilişleri listeler.",
    "giveaway end": "Devam eden bir çekilişi hemen sonlandırır ve kazananı belirler.",
    "giveaway reroll": "Biten bir çekiliş için yeniden kazanan seçer.",
    "suggest": "Sunucu yönetimine yeni bir öneri sunmanızı sağlar.",
    "suggest consider": "Bir öneriyi 'değerlendiriliyor' olarak işaretler.",
    "suggest approve": "Sunulan bir öneriyi kabul eder ve onaylar.",
    "suggest deny": "Sunulan bir öneriyi reddeder.",
    "suggest channel": "Kullanıcı önerilerinin gönderileceği kanalı belirler.",
    "ticket": "Kullanıcıların yetkililerle özel görüşebilmesi için destek talebi (Ticket) sistemini yönetir.",
    "ticket log": "Kapatılan ticket'ların geçmiş (log) kayıtlarının gönderileceği kanalı ayarlar.",
    "ticket setup": "Destek talebi (Ticket) oluşturma butonunu belirlenen kanala kurar.",
    "ticket remove": "Bir ticket kanalından kullanıcıyı çıkarır.",
    "ticket support": "Ticket'larla ilgilenecek yetkili destek rolünü belirler.",
    "ticket add": "Mevcut bir ticket kanalına başka bir kullanıcıyı dahil eder.",
    "ticket category": "Açılan ticket kanallarının hangi kategoride oluşturulacağını belirler.",

    # Eğlence ve Araçlar
    "8ball": "Sorduğunuz sorulara sihirli 8 topu tarzında rastgele cevaplar verir.",
    "say": "Bota istediğiniz bir mesajı yazdırır.",
    "joke": "Rastgele komik bir şaka anlatır.",
    "mock": "Yazdığınız yazıyı iĞnEleYici BiR tArZdA yeniden yazar.",
    "love": "İki kullanıcı arasındaki aşk uyumunu yüzdelik olarak hesaplar.",
    "rage": "Birisine olan öfkenizi dile getirir (Roleplay).",
    "rage list": "Öfke (Rage) sisteminin komutlarını listeler.",
    "rage set": "Öfke puanı hedefini ayarlar.",
    "rage remove": "Öfke puanını siler.",
    "howgay": "Kullanıcının ne kadar eşcinsel olduğunu yüzdelik olarak 'ölçer' (Eğlence amaçlı).",
    "howaustic": "Kullanıcının ne kadar otistik olduğunu yüzdelik olarak 'ölçer' (Eğlence amaçlı).",
    "iq": "Kullanıcının IQ seviyesini rastgele belirler (Eğlence amaçlı).",
    "meme": "Reddit'ten rastgele eğlenceli bir 'meme' paylaşır.",
    "cat": "Rastgele tatlı bir kedi fotoğrafı gönderir.",
    "dog": "Rastgele tatlı bir köpek fotoğrafı gönderir.",
    "coinflip": "Yazı tura atar.",
    "roll": "Belirtilen sayı aralığında rastgele bir zar atar.",
    "rps": "Botla Taş-Kağıt-Makas oyunu oynarsınız.",
    "choose": "Yazdığınız seçenekler arasından rastgele birini seçer.",
    "fact": "İlginç ve rastgele bir bilgi paylaşır.",
    "trivia": "Bilgi yarışması tarzında rastgele bir soru sorar.",
    "slap": "Bir kullanıcıyı tokatlarsınız (Roleplay).",
    "hug": "Bir kullanıcıya sarılırsınız (Roleplay).",
    "pat": "Bir kullanıcının başını okşarsınız (Roleplay).",
    "kiss": "Bir kullanıcıyı öpersiniz (Roleplay).",
    "cuddle": "Bir kullanıcıyla kucaklaşırsınız (Roleplay).",
    "bite": "Bir kullanıcıyı ısırırsınız (Roleplay).",
    "punch": "Bir kullanıcıyı yumruklarsınız (Roleplay).",
    "poke": "Bir kullanıcıyı dürtersiniz (Roleplay).",
    "lick": "Bir kullanıcıyı yalarsınız (Roleplay).",
    "boop": "Bir kullanıcının burnuna dokunursunuz (Roleplay).",
    "tickle": "Bir kullanıcıyı gıdıklarsınız (Roleplay).",
    "wave": "Bir kullanıcıya el sallarsınız (Roleplay).",
    "highfive": "Bir kullanıcıyla çak bir beşlik yaparsınız (Roleplay).",
    "cry": "Ağlarsınız (Roleplay).",
    "laugh": "Gülersiniz (Roleplay).",
    "blush": "Kızarırsınız (Roleplay).",
    "yeet": "Bir şeyi fırlatırsınız (Roleplay).",
    "dance": "Dans edersiniz (Roleplay).",
    "nsfw": "Yetişkinlere özel (+18) içerik gönderir.",
    "nsfw hentai": "+18 Anime (Hentai) görseli gönderir.",
    "nsfw rule34": "+18 Rule34 görseli gönderir.",
    "nsfw bdsm": "+18 BDSM içerikli görsel gönderir.",
    "nsfw feet": "+18 Ayak fetiş görseli gönderir.",
    "oda-kurulum": "Kullanıcıların kendi geçici ses kanallarını oluşturabileceği 'Özel Oda' sistemini kurar.",
    "ping": "Botun Discord sunucularına olan gecikme (ping) süresini gösterir.",
    "owners": "Botun sahiplerini ve yapımcılarını gösterir.",
    "banner": "Bir kullanıcının profil afişini (banner) gösterir.",
    "avatar": "Bir kullanıcının profil fotoğrafını (avatar) gösterir.",
    "about": "Kumiho bot hakkında istatistik ve genel bilgiler verir.",
    "userinfo": "Belirtilen kullanıcının hesap kurulum tarihi, rolleri vb. bilgilerini gösterir.",
    
    # Yönetim ve Ayarlar
    "givemoney": "Yönetici olarak bir kullanıcıya karşılıksız para verir.",
    "takemoney": "Yönetici olarak bir kullanıcının parasını siler.",
    "ecoban": "Kullanıcının ekonomi komutlarını kullanmasını yasaklar.",
    "ecounban": "Ekonomi komutlarından yasaklanan kullanıcının yasağını kaldırır.",
    "botban": "Kullanıcının botun hiçbir komutunu kullanmamasını sağlayacak şekilde botu yasaklar.",
    "botunban": "Bot kullanım yasağını kaldırır.",
    "sync": "Botun / (Eğik Çizgi) komutlarını sunucuyla senkronize eder.",
    "sync_roles": "Sunucudaki rolleri veritabanıyla senkronize eder.",
    "db": "Veritabanı ayarlarını ve verilerini yönetmenizi sağlar.",
    "db app": "Kullanıcı başvuruları (Örn: Yetkili alım formu) ile ilgili kayıtları yönetir.",
    "db app create": "Yeni bir başvuru formu oluşturur.",
    "db app reject": "Yapılan bir başvuruyu reddeder.",
    "db app accept": "Yapılan bir başvuruyu kabul eder.",
    "db server": "Sunucu genel ayarlarını veritabanında yapılandırır.",
    "db server update": "Sunucu ayarlarını günceller.",
    "db server role": "Sunucu rol verilerini yapılandırır.",
    "db server emoji": "Sunucu emoji verilerini yapılandırır.",
    "db server perm": "Sunucu yetki/izin verilerini yapılandırır.",
    "db text": "Metin kanalları ile ilgili kayıtları düzenler.",
    "db text delete": "Bir metin kanalı kaydını siler.",
    "db text edit": "Bir metin kanalı kaydını düzenler.",
    "db voice": "Ses kanalları ile ilgili kayıtları yönetir.",
    "db voice join": "Ses kanalına katılma log/ayarlarını düzenler.",
    "db voice stream": "Ses kanalında yayın açma log/ayarlarını düzenler.",
    "db voice switch": "Ses kanalları arası geçiş log/ayarlarını düzenler.",
    "db invite": "Sunucu davet (Invite) kayıtlarını yönetir.",
    "db invite create": "Davet oluşturma loglarını yönetir.",
    "db invite use": "Davet kullanım loglarını yönetir.",
    "db role": "Rol kayıtlarını yönetir.",
    "db role remove": "Bir rol kaydını veritabanından siler.",
    "db role add": "Veritabanına yeni bir rol kaydı ekler.",
    "db mod": "Moderasyon kayıtlarını yönetir.",
    "db mod channel": "Kanal moderasyon loglarını yönetir.",
    "db mod msg": "Mesaj moderasyon loglarını yönetir.",
    "db mod role": "Rol moderasyon loglarını yönetir.",
    "db warn": "Uyarı sistemi kayıtlarını yönetir.",
    "db warn remove": "Veritabanından bir uyarının kaydını siler.",
    "db warn add": "Veritabanına yeni bir uyarı kaydı ekler.",
    "db ticket": "Destek talebi (Ticket) veritabanı kayıtlarını yönetir.",
    "db ticket create": "Bilet (ticket) oluşturma kayıtlarını yönetir.",
    "db ticket close": "Bilet (ticket) kapatma kayıtlarını yönetir.",
    "dblog": "Botun arka planda kaydettiği detaylı veritabanı loglarını gösterir.",
    "log": "Sunucudaki log (Kayıt) kanalını ve ayarlarını yönetir.",
    "log voice": "Ses kanalı giriş-çıkış loglarını yapılandırır.",
    "log voice join": "Kullanıcıların ses kanalına katılmasını loglar.",
    "log voice stream": "Ses kanalında ekran paylaşımı/kamera açılmasını loglar.",
    "log voice switch": "Kullanıcıların bir ses kanalından diğerine geçmesini loglar.",
    "log invite": "Sunucuya davet ile girenlerin/çıkanların loglarını yapılandırır.",
    "log invite create": "Yeni bir davet linki oluşturulduğunda loglar.",
    "log invite use": "Kullanıcıların hangi davet linkini kullanarak katıldığını loglar.",
    "log set": "Loglama sisteminin açık/kapalı durumunu veya log kanalını ayarlar.",
    "log text": "Metin kanallarındaki mesaj loglarını (silinen/düzenlenen) yapılandırır.",
    "log text delete": "Kullanıcıların sildiği mesajları log kanalına gönderir.",
    "log text edit": "Kullanıcıların düzenlediği mesajların eski ve yeni halini loglar.",
    "log server": "Sunucu ayarlarında yapılan değişiklikleri loglar.",
    "log server update": "Sunucu isminin, ikonunun vb. güncellenmesini loglar.",
    "log server emoji": "Sunucuya yeni emoji eklendiğini/silindiğini loglar.",
    "log server perm": "Sunucudaki rollerin yetkilerindeki değişiklikleri loglar.",
    "log server role": "Sunucuya yeni rol eklendiğini/silindiğini loglar.",
    "log mod": "Moderatörlerin yaptığı ban, kick, timeout işlemlerini loglar.",
    "log mod channel": "Kanal açma/silme/düzenleme işlemlerini loglar.",
    "log mod msg": "Moderatörlerin sildiği kullanıcı mesajlarını loglar.",
    "log mod role": "Kullanıcılara verilen/alınan rolleri loglar."
}

def update_descriptions():
    json_path = 'web/api/commands_list.json'
    if not os.path.exists(json_path):
        print("commands_list.json not found!")
        return

    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    for category, cmd_list in data.items():
        for cmd in cmd_list:
            name = cmd["name"]
            if name in translations:
                cmd["desc"] = translations[name]

    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print("Commands successfully updated!")

if __name__ == "__main__":
    update_descriptions()
